export const randomErrorMessages = [
  "Well... That's akward.",
  "Yup, that's me. You're probably wondering how I ended up in this situation.",
  "You're not supposed to be here.",
  "So about the other night...",
  "I'm not angry, just disappointed.",
  "I swear this never happens.",
  "Houston, we have a problem.",
  "I'm not a doctor, but I think something's wrong here.",
  "I'm gonna need you to take a seat right over there.",
  "I've got a bad feeling about this.",
  "It's not a bug, it's a feature.",
  "Error 404: Message not found.",
  "I'm not lazy, I'm just on energy saving mode.",
  "I'm not sure what to do with this.",
  "I'm sorry, can you repeat the question?",
  "I'm sorry, I can't hear you over the sound of how awesome I am.",
  "I'm too sober for this.",
  "I've been expecting you.",
  "I've got 99 problems, but a glitch ain't one.",
  "If I'm not back in five minutes, wait longer!",
  "It's a trap!",
  "It's not a bug, it's an undocumented feature.",
  "Keep calm and don't touch anything.",
  "My code never has bugs. It just develops random features.",
  "No, this isn't right at all.",
  "Now where did I put that...",
  "Please hold, your call is very important to us.",
  "The cake is a lie.",
  "This is not the code you're looking for.",
  "Looks like heapy uploaded broken version again...",
  "Have you tried restarting your browser?",
  "Have you tried restarting your PC?",
  "Have you tried restarting your router?",
]

export function getRandom(array: any[]) {
  return array[Math.floor(Math.random() * array.length)]
}
